<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipo [
    <!ELEMENT equipo (pokemon+)>
    <!ELEMENT pokemon (nombre, tipo+, nivel)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT nivel (#PCDATA)>
]>

<equipo>
    <pokemon>
        <nombre>pikachu</nombre>
        <tipo>electrico</tipo>
        <nivel>50</nivel>
    </pokemon>
    <pokemon>
        <nombre>charizard</nombre>
        <tipo>fuego</tipo>
        <tipo>dragon</tipo>
        <nivel>90</nivel>
    </pokemon>
</equipo>